version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    env_file:
      - stack.env
    volumes:
      - app-data:/app/data

volumes:
  app-data: